### ISSUE TITLE
Subscriptions bug

### ISSUE THREAD

**Issue by mixmix** [ticktackim/ticktack-workplan#100]
Have had trouble reproducing this, but 2-3 users have seen it: 

`%7fpVLLTPqdgBJ9RPIgVIkTpvMEtgxlaH2saMyG0JHa4=.sha256` : 

> At first it looked good, but then it broke a few clicks later. Broke = there is nothing in "Discover", and when I click on any of my subscriptions that is blank too. macOS 10.12.6. Also my unread private messages with multiple users lose their usernames and message content, just avatars:

```
Error: no async:channel,subscriptions
    at Object.localCall (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:29:13)
    at Object.<anonymous> (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/local-api.js:37:22)
    at Object.request (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/stream.js:46:17)
    at PacketStream._onrequest (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:161:17)
    at PacketStream.write (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream/index.js:134:41)
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/muxrpc/pull-weird.js:56:15
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-stream/sinks/drain.js:24:37
    at /Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/Applications/Patchwork.app/Contents/Resources/app.asar/node_modules/pull-reader/index.js:39:14)
```

**Comment by mixmix** [comment]
oh oh this is probably people running patchwork at the same time

**Comment by mixmix** [comment]
success, found it !
